accountancy/urls.py
from django.urls import path

from . import views

app_name = 'accountancy'

urlpatterns = [
    path('', views.index, name='index'),
    path('upload', views.Upload.as_view(), name='upload'),
    path('list', views.list, name='list'),
    path('list/<int:file_id>/', views.presentation_file, name='presentation'),  # через этот путь передается id файла, который следует отобразить
    path('exist', views.exist, name='exist'),
    path('success', views.success, name='success')
]

task2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accountancy/', include('accountancy.urls')),
    path('admin/', admin.site.urls),
]

accountancy/models.py
from django.db import models


# Create your models here.
class File(models.Model):
    """

    """
    id = models.IntegerField('id файла', primary_key=True)
    name = models.CharField('имя файла', max_length=255)


class Class(models.Model):  # класс-сущность таблицы класс
    id = models.IntegerField('id класса', primary_key=True)
    name = models.CharField('имя класса', max_length=255)


class Group(models.Model):  # класс-сущность таблицы группа
    id = models.IntegerField('id группы', primary_key=True)
    code = models.IntegerField('номер группы')


class Note(models.Model):   # класс-сущность таблицы запись
    id = models.IntegerField('id записи', primary_key=True)
    code = models.IntegerField('номер записи')
    incoming_liability = models.FloatField('входящий пассив')
    incoming_asset = models.FloatField('входящий актив')
    debit = models.FloatField('обороты-дебет')
    credit = models.FloatField('обороты-кредит')
    file_id = models.ForeignKey(File, on_delete=models.CASCADE)
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE)
    group_id = models.ForeignKey(Group, on_delete=models.CASCADE)

accountancy/forms.py
from django import forms
from .models import File


class FileUploadForm(forms.ModelForm):  # класс, который отвечает за форму, для загрузки файла, наследуется от django класса
    file = forms.FileField(label='', )
    # TODO: file name duplicate validation

    class Meta:
        model = File
        exclude = ('id', 'name')

accountancy/views.py
from django.shortcuts import render
from django.shortcuts import reverse
from accountancy.utility.upload import parse_file_bd
from accountancy.forms import FileUploadForm
from accountancy.models import File
from django.views.generic import CreateView
from django.http import HttpResponseRedirect
from accountancy.utility.export import export_file
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import redirect


# Create your views here.
def index(request):
    return render(request, 'accountancy/welcome_page.html')


class Upload(CreateView):
    model = File
    template_name = 'accountancy/upload.html'
    form_class = FileUploadForm

    def get_success_url(self):
        return reverse('success')

    def post(self, request, *args, **kwargs):
        form = FileUploadForm(request.POST, request.FILES)
        name = request.FILES['file'].name
        if form.is_valid():
            if parse_file_bd(request.FILES['file'], request.FILES['file'].temporary_file_path(),
                             name) == -1:  # если файл с таким именем уже был, то переходим на соответствующий шаблон
                return HttpResponseRedirect('exist')
            else:
                return HttpResponseRedirect('success')
        return render(request, 'accountancy/upload.html', {'form': form})

    def get(self, request, *args, **kwargs):
        form = FileUploadForm()
        return render(request, 'accountancy/upload.html', {'form': form})


def list(request):
    names_of_files = File.objects.all()
    return render(request, 'accountancy/list.html', {'names_of_files': names_of_files})


def presentation_file(request, file_id):
    name = File.objects.get(id=file_id).name
    export_list = export_file(file_id)
    return render(request, 'accountancy/presentation.html',
                  {'data': export_list,
                   'name': name})  # передается список уже загруженных файлов в соответствующий шаблон.


def success(request):
    return render(request, 'accountancy/success.html')


def exist(request):
    return render(request, 'accountancy/err_exist.html')

task2/templates/accountancy/err_exist.html
{% extends 'base.html' %}
{% block title %}Успех!{% endblock %}
{% block content %}
        <h1 data-name="Файл уже существует.">Файл уже существует.</h1>
        <a href="{% url 'accountancy:upload' %}" class="glo">Выбрать другой</a>
        <a href="{% url 'accountancy:index' %}" class="glo">Вернуться на главную</a>
{% endblock %}

task2/templates/accountancy/list.html
{% extends 'base.html' %}
{% block title %}Список загруженных файлов{% endblock %}
{% block content %}
    <h1 data-name="Загруженные файлы:">Загруженные файлы:</h1>
    {%  if names_of_files %}
        {% for i in names_of_files %}
            <p><a href="{% url 'accountancy:presentation' i.id %} " class="glo">{{i.name}} </a></p>
        {%  endfor %}
    <hr>
    {% else %}
        <h1 data-name="Ни одного файла не загружено.">Ни одного файла не загружено.</h1>
    {% endif %}
    <a href="{% url 'accountancy:upload' %}" class="glo">Загрузить новый</a>
    <a href="{% url 'accountancy:index' %}" class="glo">Вернуться на главную</a>
{% endblock %}

task2/templates/accountancy/presentation.html
{% extends 'base.html' %}
{% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
{#    <link rel="stylesheet" href="{% static 'css/presentation.css' %}"/>#}
{#    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">#}
{% block title %}
    {{ name }}
{% endblock %}
{% block content %}
    <table cellspacing="0">
        <tr>
            <td rowspan="2" class="border-bold bold" >Б/сч</td>
            <td colspan="2" class="border-bold bold">ВХОДЯЩЕЕ САЛЬДО</td>
            <td colspan="2" class="border-bold bold">ОБОРОТЫ</td>
            <td colspan="2" class="border-bold bold">ИСХОДЯЩЕЕ САЛЬДО</td>
        </tr>
        <tr>
            <td class="border-bold bold">Актив</td>
            <td class="border-bold bold">Пассив</td>
            <td class="border-bold bold">Дебет</td>
            <td class="border-bold bold">Кредит</td>
            <td class="border-bold bold">Актив</td>
            <td class="border-bold bold">Пассив</td>
        </tr>
        {% for i in data %}
        <tr>
        {% if i|length_is:"7" %}
            {% if i|first < 100 or i|first == 'ПО КЛАССУ' or i|first == 'БАЛАНС' %}
                {% for j in i %}
                <td class="right bold">{{j}}</td>
                {% endfor %}
            {% else %}
                {% for j in i %}
                <td class="right">{{j}}</td>
                {% endfor %}
            {% endif %}
        {% else %}
            <td colspan="7" class="bold ">{{i|first}}</td>
        {% endif %}
        </tr>
    {% endfor %}
    </table>
{% endblock %}

task2/templates/accountancy/success.html
{% extends 'base.html' %}
{% block title %}Успех!{% endblock %}
{% block content %}
        <h1 data-name="Файл успешно загружен.">Файл успешно загружен.</h1>
        <a href="{% url 'accountancy:upload' %}" class="glo">Загрузить ещё</a>
        <a href="{% url 'accountancy:index' %}" class="glo">Вернуться на главную</a>
{% endblock %}

task2/templates/accountancy/upload.html
{% extends 'base.html' %}
{% block title %}Загрузка данных из exel файла в субд {% endblock %}
{% block content %}
    <form enctype="multipart/form-data" method="post" class="btn">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Загрузить" class="btn" />
    <a href="{% url 'accountancy:index' %}" class="glo">Вернуться на главную</a>
</form>
{% endblock %}

task2/templates/accountancy/welcome_page.html
{% extends 'base.html' %}
{% block title %}Главная страница {% endblock %}
{% block content %}
    <h1 data-name="Выберите действие::">Выберите действие:</h1>
    <a href="{% url 'accountancy:list' %}" class="glo">Список загруженных файлов</a>
    <a href="{% url 'accountancy:upload'%}" class="glo">Загрузить файл</a>
{% endblock %}

task2/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/presentation.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
	<title>{% block title %}Бухгалтерия{% endblock %}</title>
</head>
<body>
{% block content %} {% endblock %}
</body>
</html>